### ISSUE TITLE
Issues Running Payload On macOS Big Sur

### ISSUE THREAD

**Issue by iwantmyhatback** [krakrukra/PocketAdmin#10]
Ive had my PocketAdmin for a little while but didn't get around to using it until the same day I upgraded my mac to the new "Big Sur" OS, so I'm not sure if this is a new issue or an old issue. I am having a similar issue to a previous one reported where the OS gave me an error when plugging in the drive:

<img width="264" alt="Screen Shot 2020-11-14 at 7 38 10 PM" src="https://user-images.githubusercontent.com/50348381/99161332-49945900-26bf-11eb-810d-9c9070bfa504.png">

- Ejecting results in ejection
- Ignore results in the drive only showing unmounted in disk utility
- Initializing allows me to see the drive in the disk utility allegedly mounted as `disk2` but i am unable to interact with it or even see the disk in the `/Volumes` directory.

I see that in the previous issue with the drive not being recognized by mac the instructions you provided there was to format the visible drive as an FAT-32 partition, but the person who reported the issue didn't reply so I'm not sure what happened in that case. I followed your advice (also making the required selection to format it as MBR). I had to change the name of the drive to "USBDRIVE1" as it wouldn't allow me enough characters to name it "Ordinary Flash Drive Media" on the macOS disk utility. (Noting that incase it may be causing an issue)

 The disk now shows up as:

` /dev/disk2 (external, physical):`
`   #:                       TYPE NAME                                   SIZE             IDENTIFIER`
`   0:                       FDisk_partition_scheme              *100.9 MB     disk2`
`   1:                       DOS_FAT_32 ⁨USBDRIVE1⁩               100.9 MB     disk2s1`

I am able to interact with the drive now and it mounts without error, but the USB features do not seem to be in effect anymore. I do not get payload execution upon insertion, and toggling the caps lock key has no effect on the drive when it is inserted. To test i am trying to use the following simple payload:

`WAITFOR_INIT`
`DELAY 1000`
`ALLOW_EXIT`
`DELAY 1000`
`GUI SPACE`
`DELAY 1000`
`STRING terminal`
`DELAY 1000`
`ENTER`
`DELAY 1000`

Any input or troubleshooting steps would be greatly appreciated.

Notes / possibly useful info:
- Before reformatting the partition i also got the mac unknown keyboard wizard a couple times
- Drive is acting as expected on windows machines
- I have access to Mac / Windows / Rasbian(debian) systems if needed to troubleshoot

**Comment by krakrukra** [comment]
Previous issue #5 was in fact resolved by reformatting the drive and changing the text editor, the
person that created it contacted me in 2 different places, so our discussion continued outside of github.

When you were naming the drive as "USBDRIVE1" you were most likely setting the FAT volume label,
which is limited in length to 11 characters. This is certainly not the cause of your problem. "Ordinary 
Flash Drive" is the drive name used in a BIOS menu, i guess your mac showed it because the drive
originally had no FAT label.

In your case I think you have done everything correctly up until the point where you created your payload
file. I remember that last time I tested default text editor on macos (TextEdit) it was adding a lot of weird
stuff into the text files, as if it is not a text editor but some office program. So, that made the payload files
created by it not readable by the device. You can try to install a different text editor on your mac,
eg. notepad++ and it should work. Or, you could make your payload file on eg. windows (notepad), 
then use it on mac. If it works, than you know that text editor was in fact the problem.

Unknown keyboard wizard is an apple thing. This shows up whenever you use a keyboard that was not 
made by apple. You could use VID/PID changing to avoid that (set these to values of some apple keyboard).

**Comment by iwantmyhatback** [comment]
Unfortunately the issue is not from the text editor as i used a `touch` command and CLI `nano` to create the payload file, do you perhaps have any other suggestions for things to check that could be causing an issue? 

Just an FYI for you though if you'd like to remove the formatting on your mac text editor you can go into the Text Edit preferences and change the format from rich text to plain text and i think that would remove any strange formatting on your machine!

**Comment by krakrukra** [comment]
OK. Then check if you actually have a proper MBR partition table and you are formatting the first
partition, not the whole drive. This looks kind of weird:
> 0: FDisk_partition_scheme *100.9 MB disk2
> 1: DOS_FAT_32 ⁨USBDRIVE1⁩ 100.9 MB disk2s1

If I understand this correctly, full disk size and first partition size are the same, which should not normally
be the case. Usually partition table tools leave like 1 or 2 MiB of free space after the MBR, so if you have a
single partition it is normally 94-95 MiB in size (full disk is 96MiB).

Since you have a windows machine, try doing this: https://youtu.be/jhsEZJUVx_E 
Start following the video from 20 second mark, starting with a right click on windows button. 
There, I select PocketAdmin's USB drive, erase all partitions and create a new one with FAT filesystem.

If your payloads still don't work, then it might be some weird filesystem error that formatting tools do
not fix for some reason. In this case, overwriting all data on the PocketAdmin's disk to 0xFF bytes could
help. Follow this video to install and use HxD hex editor:  https://youtu.be/aTmnEvwCHiA 
Make sure to select the right drive before overwriting. After that, Follow steps from the first video again
and see it it solved the problem.

**Comment by iwantmyhatback** [comment]
I was able to resolve using the first part of your response by formatting using the Windows Disk Manager, I guess that it partitions FAT differently than the Mac disk utility does. I have verified that the Mac disk utility was the issue by following that instruction on a second PocketAdmin from "Factory", just repartition and everything is good to go.

I realized before formatting the second PocketAdmin that the Mac was seeing the original partition as a Linux partition for some reason, so just leaving this information here for anyone with issues in the future (Use the Windows Disk Management Tool):

**Factory Default PocketAdmin Partition**
`/dev/disk2 (external, physical):`
`   #:                       TYPE NAME                    SIZE       IDENTIFIER`
`   0:     FDisk_partition_scheme                        *100.9 MB   disk2`
`   1:                      Linux ⁨⁩                        99.9 MB    disk2s1`

**Mac Disk Utility PocketAdmin Partition**
`/dev/disk2 (external, physical):`
`#: TYPE NAME SIZE IDENTIFIER`
`0: FDisk_partition_scheme *100.9 MB disk2`
`1: DOS_FAT_32 ⁨USBDRIVE1⁩ 100.9 MB disk2s1`

**Windows Disk Manager PocketAdmin Partition**
`/dev/disk3 (external, physical):`
`   #:                       TYPE NAME                    SIZE       IDENTIFIER`
`   0:     FDisk_partition_scheme                        *100.9 MB   disk3`
`   1:             Windows_FAT_16 ⁨NEW VOLUME⁩              99.6 MB    disk3s1`

Thanks for your help @krakrukra
