### ISSUE TITLE
How to create new or edit existing keyboard layout ?

### ISSUE THREAD

**Issue by mrshellx** [krakrukra/PocketAdmin#11]
Hello,
I want add new keyboard layout and edit existing one, in tr_TR layout some keys not printing (like '_ç_', '_ö_'), how can i do this ?

**Comment by krakrukra** [comment]
Keyboard layout files are only used to translate ASCII-printable characters into correct
keycode + modifiers combination. Since the characters which you are trying to print are 
not ASCII-printable, you will not be able to use them directly in payload files (eg. inside of
a STRING command). If you just want some way to type these characters in, you could 
instead use the KEYCODE command. In your case you would use "KEYCODE 0x36" for "ö", and
"KEYCODE 0x37" for "ç" (you can also add modifiers like "SHIFT KEYCODE 0x37")
for mor information about keycodes, you can check out this document (pages 52 to 59):
https://usb.org/document-library/hid-usage-tables-121
