### ISSUE TITLE
SHOW_FAKE_CAPACITY does not work

### ISSUE THREAD

**Issue by usama7628674** [krakrukra/PocketAdmin#16]
I tried many times but original size does not change on windows 11.
![image](https://user-images.githubusercontent.com/29252277/140556390-6a8ebc88-e634-449a-a750-63abd1633d00.png)

![image](https://user-images.githubusercontent.com/29252277/140556520-52989bed-56ff-40e2-8c4d-7500037d23e0.png)

**Comment by usama7628674** [comment]
Revision is `1.3`
Firmware is updated to latest version `firmware_13003.dfu`

**Comment by krakrukra** [comment]
That is probably because you have not reformatted the partition, as shown in this video:
https://www.youtube.com/watch?v=ZsajkLqX0K4  (starting from 7:37 timestamp)

The thing is, windows file explorer shows available partitions, not all available space on the drive.
And the MBR partition table still has the old partition size written in it, and possibly, existing filesystem
has this old information written somewhere as well. I found that just reformatting the partition
via windows disk management utility fixes that.

**Comment by usama7628674** [comment]
Yeah, formatting drive after setting fake capacity fixed the issue. Thanks!
