### ISSUE TITLE
String type slowly in Windows 11

### ISSUE THREAD

**Issue by leomacin** [krakrukra/PocketAdmin#17]
Pocketmadmin version 1300X types slowly and even stuck in the middle of String Command in Windows 11.
This is more clear in Windows 11 when you are typing on Notepad. It doesn't happen in Linux and Windows 10 or earlier.

**Comment by krakrukra** [comment]
Just now noticed this open issue, oops. I will make some tests on a windows 11 PC and try to recreate 
this problem and see what can be done. Meanwhile, you can try adding a "STRING_DELAY 1" command 
to the beginning of payload.txt and check if it helps or not. Maybe try some other values too, eg 1, 2, 5, 10

**Comment by krakrukra** [comment]
OK, so on my test machine with windows 11 everything works without any problem. Can you post 
exactly the payload that you have that is getting stuck for you?

**Comment by krakrukra** [comment]
Actually, after doing some more testing I managed to recreate this problem. This happens specifically on windows 11 version of notepad (not in runline window or powershell, etc). Sometimes typing gets stuck and continues  only when you press or hold a button on a normal keyboard. Seems like notepad on win 11 sometimes can not handle very fast typing. I artificially slowed it down with "STRING_DELAY 5" command inside my payload and 
the problem is gone now.
