### ISSUE TITLE
Unable to format

### ISSUE THREAD

**Issue by RChadwick7** [krakrukra/PocketAdmin#4]
I made one of these a while ago, but was never successful flashing it, so I put it aside. I saw the Wili was updated, and gave it a try, and it worked! I plug it in, and it asks to format the drive. Unfortunately, it fails. What am I missing?

**Comment by krakrukra** [comment]
Yes, I think I remember. You have built it before the 1.3 release, so you
should have 1.2 revision hardware, correct? The flashing procedure for
these is shown in this video (fragment from 0:00 to 4:43) :
https://www.youtube.com/watch?v=t0oajBFZcZY&feature=youtu.be
Is this the procedure you have followed?
Because you cannot run 13000 firmware on older hardware, in your case
you would need 12005 firmware

**Comment by krakrukra** [comment]
If you followed the right procedure and it fails to format anyway, it might
be because the seller of the W25Q256FVFG memory chip did not ship it to
you pre-erased, as it should be. In this case, you should erase all the memory
yourself. If you flashed 13000 firmware into 1.2 device you should also erase
all memory before flashing the correct 12005 firmware. The easiest way to do
so is to flash 12003 firmware (disk size should become 32MiB), and then overwrite
all memory to 0xFF bytes using some hex editor (on linux I use hexedit). The process
could take quite a bit of time, like 10 min, because 12003 firmware was not very good.

**Comment by RChadwick7** [comment]
I originally assumed I made some mistake building it, but it looks like you're right. I flashed 12003, and suddenly I had a 32MB flash drive. I was lazy, so I tried doing a long format, but that didn't work. I used HxD to flash FF's to everything, flashed 12005, and I have a 24MB drive now. Is it supposed to be 32MB?

**Comment by RChadwick7** [comment]
Also, if new firmware won't be compatible with old hardware, is it easy/possible to upgrade the hardware to 1.3?

**Comment by krakrukra** [comment]
Yes, it is supposed to be 24MiB. This is due to the fact that versions 12004 and up
have a Flash Translation Layer built in, and 8MiB are allocated for overprovisioning
and other stuff like that. The 12003 firmware did not have that, and directly
 translated logical block addresses into physical block addresses.

**Comment by RChadwick7** [comment]
Great, thanks. I looked at the hardware, so I'm guessing it's not practical to physically upgrade :)

**Comment by krakrukra** [comment]
Well yes, you would have to buy new PCB's and memory chips to upgrade the hardware.
Does your device seem to work OK with 12005 right now?

**Comment by RChadwick7** [comment]
Yes, so far. I'm running H2testw (Endless verify), and it passed. Now I have to figure out how to use it :)

**Comment by krakrukra** [comment]
OK, good
