### ISSUE TITLE
Pocket Admin not readable by MacBook

### ISSUE THREAD

**Issue by Vanceagher** [krakrukra/PocketAdmin#5]
Is the Pocket Admin supposed to be read by a MacBook? If not, how can I get this to work? Or will I have to use a Windows computer.

`Volume type : Physical Device
BSD device node : disk3
Connection : USB
Device tree path : IODeviceTree:/PCI0@0/OHC2@6
Writable : No
Is case-sensitive : No
Volume capacity : 100,925,440
Available space (Purgeable + Free) : 0
Purgeable space : 0
Free space : 0
Used space : 100,925,440
Owners enabled : No
Is encrypted : No
Can be verified : No
Can be repaired : No
Bootable : No
Journaled : No
Disk number : 3
Media name : Ordinary Flash Drive Media
Media type : Generic
Ejectable : Yes
Solid state : No
S.M.A.R.T. status : Not Supported
`

![Screen Shot 2020-08-07 at 10 37 33 PM](https://user-images.githubusercontent.com/48972091/89700743-ac2acb80-d8fe-11ea-9c9a-212e4bf8a933.png)

![Screen Shot 2020-08-07 at 10 35 28 PM](https://user-images.githubusercontent.com/48972091/89700696-58b87d80-d8fe-11ea-82ef-d2c90f896648.png)

**Comment by krakrukra** [comment]
It should be readable on macbooks, though it is not very extensively tested there.
First thing to do is to reformat the drive, make 1 partition and format it as FAT filesystem,
then try to plug the device in again.

**Comment by krakrukra** [comment]
I have actually just now installed macos high sierra and noticed that default text editor (TextEdit)
adds a lot of extra data into the text files, so you might need a different text editor that does not
do that, in order to write payload files. But with properly written payload file the device has worked
OK on my machine, both for storage and keyboard.
